### ISSUE TITLE
Add integer and faux division support to bn_format

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezor-crypto#102]
Add support for formatting as integers (e.g. no decimal point - I think a negative `decimals` works for this, but I'm not sure if that's an intentional part of the API) and division by a power of 10 while maintaining the `decimals`.

Also a flag to force trailing zeroes would be useful. I think the best way to implement this would be adding `divisor` for the faux division and `trailing` for the trailing zeroes. Making the `decimals` functionality explicit should do for the integer formatting.

I implemented a workaround in trezor/trezor-mcu#196 but ideally this should become functionality of `bn_format`

**Comment by saleemrashid** [comment]
I can work on this, just wanted your thoughts on the API

**Comment by prusnak** [comment]
What is faux division?

**Comment by saleemrashid** [comment]
@prusnak I should have worded that better. :smile: Basically, division by a power of 10 (like `decimals` does) but still truncating it to `decimals`. e.g. If I want to divide by 10^10, with 6 decimal places, I would use a `decimals` of 6, and a `divisor` of 4.

**Comment by saleemrashid** [comment]
Referenced workaround: https://github.com/saleemrashid/trezor-mcu/blob/nem/firmware/nem2.c#L724-L741

**Comment by prusnak** [comment]
Ah, I see.

For the API I would like the following:

1) use `decimals=0` for formatting integers (currently `decimals=0` will print `2.0` instead of `2`)
2) add `bool trailing` to specify whether we want trailing zeroes
3) add `int truncate` to specify we want to at most X decimals (should we round the last digit? probably not)

**Comment by saleemrashid** [comment]
@prusnak What about `divisor` instead of `truncate`? It's more intuitive and `divisor == 0` will give the old behaviour. Also, I would need to check if I need this anywhere, but we could support a negative `divisor` that multiplies it by a power of 10.

**Comment by prusnak** [comment]
Go ahead!
