### ISSUE TITLE
[Support] Need guideline and building unitTest for osx

### ISSUE THREAD

**Issue by meow0703** [trezor/trezor-crypto#112]
Dear team,
We love your work, please help support us on how to build current unitTest for bip32 (available in sourcecode). We tried building but still got below error.
Many thanks
John
![image](https://user-images.githubusercontent.com/19224355/29751927-efd90976-8b7e-11e7-933e-63d93a1b84fc.png)

**Comment by prusnak** [comment]
You need to include modm-donna-32bit.c into your project.
