### ISSUE TITLE
How Base58 encoding algorithm works?

### ISSUE THREAD

**Issue by mrbuzz** [trezor/trezor-crypto#113]
I'm trying to understand your implementation of the Base58 encoding algorithm: 

    bool b58enc(char *b58, size_t *b58sz, const void *data, size_t binsz)
    {
	    const uint8_t *bin = data;
	    int carry;
	    ssize_t i, j, high, zcount = 0;
	    size_t size;

	    while (zcount < (ssize_t)binsz && !bin[zcount])
		    ++zcount;

	    size = (binsz - zcount) * 138 / 100 + 1;
	    uint8_t buf[size];
	    memset(buf, 0, size);

	    for (i = zcount, high = size - 1; i < (ssize_t)binsz; ++i, high = j)
	    {
		    for (carry = bin[i], j = size - 1; (j > high) || carry; --j)
		    {
			    carry += 256 * buf[j];
			    buf[j] = carry % 58;
			    carry /= 58;
		    }
	    }

	    for (j = 0; j < (ssize_t)size && !buf[j]; ++j);

	    if (*b58sz <= zcount + size - j)
 	    {
		    *b58sz = zcount + size - j + 1;
		    return false;
	    }

	    if (zcount)
		    memset(b58, '1', zcount);
	    for (i = zcount; j < (ssize_t)size; ++i, ++j)
		    b58[i] = b58digits_ordered[buf[j]];
	    b58[i] = '\0';
	    *b58sz = i + 1;

	    return true;
    }

In particular I do not understand these lines: 

 - `size = (binsz - zcount) * 138 / 100 + 1;`
 - `carry += 256 * buf[j];`

what do they precisely do? Thanks for sharing your code

**Comment by saleemrashid** [comment]
The Base58 implementation is from https://github.com/luke-jr/libbase58. If you are looking to understand it, Bitcoin Core has a well-documented, but otherwise quite similar, implementation at https://github.com/bitcoin/bitcoin/blob/master/src/base58.cpp
