### ISSUE TITLE
bitcoin miner detected in qt wallet

### ISSUE THREAD

**Issue by fletchuk1** [trezor/trezor-crypto#116]
My AV (Sophos) detected a bitcoin miner in the qt wallet install file.

Any comments please?

**Comment by prusnak** [comment]
This repository has nothing to do with bitcoin qt wallet.

But I can give comment anyway: I am pretty sure this is a false positive as it makes sense bitcoin miner and bitcoin qt wallet share some code and thus it will trigger the false alarm.
