### ISSUE TITLE
MEMSET_BZERO optimized out for automatic variables

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezor-crypto#127]
GCC optimizes out the `memset` call for automatic variables, such as https://github.com/trezor/trezor-crypto/blob/8d8bc9c762b504ee8c66f94d93600d417d92841e/bip39.c#L66-L69

Using `volatile` does not solve the issue because `memset` discards the qualifier.

One possible solution would be to define `MEMSET_BZERO` as `explicit_bzero` from Newlib in the firmware. Or we could implement our own version so other dependent projects benefit from it. It is simply a call to `memset(buffer, 0, size)` but the compiler will not optimize it out.

**Comment by prusnak** [comment]
I like explicit_bzero approach, because it seem more standard.

**Comment by prusnak** [comment]
Fixed in b7f73ee3ff78e09c266a30dbc31407558d471615

**Comment by saleemrashid** [comment]
@prusnak Have you confirmed that outputs the correct code with the ARM toolchain?

**Comment by prusnak** [comment]
Yes, it seems that it does (explicit_bzero calls bzero which calls memset with second argument set to 0).

**Comment by prusnak** [comment]
Updated trezor-mcu in https://github.com/trezor/trezor-mcu/commit/4a2d68acb99f57660230d2e509f01c44db85be10

Updated trezor-core in https://github.com/trezor/trezor-core/commit/ea116d742ade46d10bc6e948078ace4edab5b703

**Comment by saleemrashid** [comment]
@prusnak I meant, have you checked the compiled code is correct (i.e. it is not being optimized out)?

**Comment by prusnak** [comment]
Yes, I was checking that in Binary Ninja. :-)
