### ISSUE TITLE
random32 vs. random_buffer

### ISSUE THREAD

**Issue by peter-conalgo** [trezor/trezor-crypto#132]
Looks like recent commits have picked `random32()` as the lowest common denominator for generating randomness.

That's ok, but in my case, I would rather base things on `random_buffer()` due to the way bits are generated on my platform.

IMHO, both functions should be available for override or customization, and probably `random_buffer` should be the more basic once. On the one hand, it's easy to ask for a 4-byte random buffer, but building a byte string from a number of calls to a 32-bit function has the potential for bugs.

Alternatively, marking `random_buffer()` with weak linkage would solve my needs.

**Comment by saleemrashid** [comment]
To be clear, `trezor-crypto` is designed first and foremost for the TREZOR device, where the RNG is read one word at a time.

As long as any changes you make don't affect that, you should be good.

**Comment by peter-conalgo** [comment]
Making `random_buffer()` a weak symbol is the way to go then.

**Comment by prusnak** [comment]
Closed in favor of #133
