### ISSUE TITLE
Trezor-crypto Documentation

### ISSUE THREAD

**Issue by alieslam** [trezor/trezor-crypto#138]
Hi Guyz, 
Is there by any chance guyz you will be providing a documentation for the trezor-crypto library(functionalities&methods)? the library is really neat and well implemented, and I am studying it to see if I can integrate it in my current embedded crypto project, I am trying to go along with the examples, but I think it will be better if there's a simple documentation explaining the supported functionalities of the library along with each method. 
Thanks,

**Comment by prusnak** [comment]
We have lots of comments in the source code. If it's not obvious what the function does, please send a pull request with your documentation additions.
