### ISSUE TITLE
trezor sig can't pass etherscan verification

### ISSUE THREAD

**Issue by leochan007** [trezor/trezor-crypto#139]
https://www.myetherwallet.com/signmsg.html

use trezor to sign message via myetherwallet.
it will fail on https://etherscan.io/tokenupdateverifysig.

**Comment by prusnak** [comment]
There are multiple sign/verify implementation for Ethereum. We will provide a fixed one once there is a consensus which one to use. Maybe https://github.com/ethereum/EIPs/pull/712 ?

**Comment by leochan007** [comment]
@prusnak i ‘ve already deployed erc20 token. then i wanna update the website. it failed when verifying msg via sig which is generated by trezor. how to select specified implementation on myetherwallet?

**Comment by prusnak** [comment]
You can't.

**Comment by amicorumlive** [comment]
Can someone suggest another way to verify the contract?  we are stuck with this page and need the information updated

**Comment by davidfarina** [comment]
Is there a temporary possibility to verify the message for example on a backend server?

**Comment by prusnak** [comment]
New Trezor firmare (1.6.2 for T1 and 2.0.7 for T2) should be able to sign/verify it.
