### ISSUE TITLE
Possible inconsistency in deterministic ECDSA signature computation

### ISSUE THREAD

**Issue by backslash47** [trezor/trezor-crypto#168]
Hello,
I am working on a project, where I want to sign a hash with nist256p1 curve. I have three implementations:

Java - using BouncyCastle with SHA256withECDDSA scheme
Javascript - using elliptic.js with p256 curve
Trezor - using nist256p1 curve

All three implementations are producing correct signatures validable with other implementations. The problem is that for some inputs, the Trezor is producing different signatures (only S component is different).

I am not able to debug the code myself, so I am at least attaching input data, which is producing different results:

hash to sign: ba01d28a1e5b51f66df62d36c478e993c35f4509dbfc590783d759f173921c3d
private key: 2a400b882757e616ed238d0d289884544542f33407d26b01b53964d3a768539e
java/javascript signature: 7da1b8268e1272d7471eef58fa0884108073c09d5efdae0143da5d281019682ea5ea9d0d289b7b15fc861c01418fda56642be628560fe4d7ccdede930e620b5d

trezor signature without first byte: 7da1b8268e1272d7471eef58fa0884108073c09d5efdae0143da5d281019682e5a1562f1d76484eb0379e3febe7025a958bb14855107b9ad26daec2fee0119f4

The signing code is:
`signature = nist256p1.sign(privateKey, hash, False)`
`signature = signature[1:65]`

**Comment by prusnak** [comment]
Hi Matus!

In ECDSA, there are still two valid signatures - one being `(R,S)`, the other one being `(R,n-S)` where `n` is the used curve's order.

In Trezor we want signatures to be deterministic and unambiguous (Bitcoin even mandates this), so we create so-called canonical signatures, where `S <= n/2` (we just pick the smaller one from `S` and `n-S`, see https://github.com/trezor/trezor-crypto/blob/a7463bcb852f1b553a941e8dd753b87ca9a88d57/ecdsa.c#L791-L795

The other libraries you use, don't do this by default (maybe there is an option for this somewhere, maybe not).

Proof in Python:

``` python
>>> x='7da1b8268e1272d7471eef58fa0884108073c09d5efdae0143da5d281019682ea5ea9d0d289b7b15fc861c01418fda56642be628560fe4d7ccdede930e620b5d'
>>> y='7da1b8268e1272d7471eef58fa0884108073c09d5efdae0143da5d281019682e5a1562f1d76484eb0379e3febe7025a958bb14855107b9ad26daec2fee0119f4'
>>> x[:64] == y[:64]
True
>>> x[64:]
'a5ea9d0d289b7b15fc861c01418fda56642be628560fe4d7ccdede930e620b5d'
>>> y[64:]
'5a1562f1d76484eb0379e3febe7025a958bb14855107b9ad26daec2fee0119f4'
>>> xx = int(x[64:], 16)
>>> yy = int(y[64:], 16)
>>> hex(xx+yy)
'0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551'
```

That means trezor S1 and yourlib S2 equal to value which you see above, which is exactly order of nist256p1 curve, which means `S1 + S2 = n => S1 = n - S2`.

**Comment by prusnak** [comment]
Some example code in Java (from BitcoinJ library): https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/ECKey.java#L528-L554

**Comment by backslash47** [comment]
Thanks for quick response.

You were right. I already found a way to enable it in elliptic.js

**Comment by prusnak** [comment]
Great! Leaving elliptic.js source code as reference too:

https://github.com/indutny/elliptic/blob/776c9b0e99832ab9fa6c5fa6f684c484ca5265b2/lib/elliptic/ec/index.js#L144-L148
