### ISSUE TITLE
Improper naming of a signature recovery function.

### ISSUE THREAD

**Issue by clementnuss** [trezor/trezor-crypto#180]
The `ecdsa_verify_digest_recover(...)` function only recovers an address from a signature and a hash, and does not verify it.
The name is is misleading and could be wrongly used IMO.

https://github.com/trezor/trezor-crypto/blob/9c2cfb04704b1419e7d1aebbb21b192fbf49644d/ecdsa.c#L1028

**Comment by prusnak** [comment]
Thanks!
