### ISSUE TITLE
[bip32] array size of public_key is 33 but the size of uncompressed key is 64

### ISSUE THREAD

**Issue by KimiWu123** [trezor/trezor-crypto#199]
in bip32.h, public key size is 33, `uint8_t public_key[33];` as following,
```
typedef struct {
	uint32_t depth;
	uint32_t child_num;
	uint8_t chain_code[32];

	uint8_t private_key[32];
	uint8_t private_key_extension[32];

	uint8_t public_key[33];
	const curve_info *curve;
} HDNode;
```

If we follow the following path,
`hdnode_get_address` -- > `ecdsa_get_address` --> `ecdsa_get_address_raw` --> `ecdsa_get_pubkeyhash` 
```
// function ecdsa_get_pubkeyhash
	if (pub_key[0] == 0x04) {  // uncompressed format
		hasher_Raw(hasher_pubkey, pub_key, 65, h);
	}
```
the input public key of `ecdsa_get_address` is `node->public_key` which is 33 bytes, but in the above case, memory out of 33 bytes (index of 33 to 63) may be touched. It may cause program crash...

**Comment by prusnak** [comment]
It won't be touched, because the first byte will never be 0x04.

**Comment by KimiWu123** [comment]
Hi @prusnak ,

Sure, I know the prefix of compressed public key will never be 0x04. What if users input incorrect key accidentally?

**Comment by prusnak** [comment]
The key in the HDNode is always computer, never entered directly from user.
