### ISSUE TITLE
bip39bruteforce example addresses are recognized as invalid

### ISSUE THREAD

**Issue by leto** [trezor/trezor-crypto#200]
I tried to use the example addresses which are listed in the source code of bip39bruteforce, but they are "invalid":
```
$ ./bip39bruteforce 1JAd7XCBzGudGpJQSDSfpmJhiygtLQWaGL
"1JAd7XCBzGudGpJQSDSfpmJhiygtLQWaGL" is not a valid address
$ ./bip39bruteforce 1N3uJ5AU3FTYQ1ZQgTMtYmgSvMBmQiGVBS
"1N3uJ5AU3FTYQ1ZQgTMtYmgSvMBmQiGVBS" is not a valid address
```
on macOS 10.13.4 compiled with `Apple LLVM version 9.1.0 (clang-902.0.39.1)`

**Comment by prusnak** [comment]
Fixed in 8434b2468cef18f582ee6470d22e16f018f1b72a

Thanks!
