### ISSUE TITLE
ECDSA signing

### ISSUE THREAD

**Issue by f4GGT** [trezor/trezor-crypto#204]
How do I generate the Recovery ID? Ethereum transactions uses v,r,s values how do I generate the value v ? 

is there any tests written on this could you please advice and share the line of code ?

**Comment by prusnak** [comment]
Very simple code search for the word recover will find these results:

https://github.com/trezor/trezor-crypto/blob/0c622d62e1f1e052c2292d39093222ce358ca7b0/ecdsa.c#L1028

https://github.com/trezor/trezor-crypto/blob/0c622d62e1f1e052c2292d39093222ce358ca7b0/tests/test_check.c#L3269
