### ISSUE TITLE
ECDH?

### ISSUE THREAD

**Issue by quartzjer** [trezor/trezor-crypto#23]
This isn't an issue, just curious if anyone has considered adding ECDH support alongside ECDSA? (at a glance it should be pretty straight forward, I may give it a try if nobody else has yet)

**Comment by prusnak** [comment]
In which particular ECDH usecase would you like to use TREZOR for?

**Comment by quartzjer** [comment]
I'm looking to use this library in https://github.com/telehash/telehash-c to support a new bitcoin-stack based cipher set and we use ECDH for ephemeral forward secrecy, that's the only missing function to make this lib usable (I think, still evaluating).

**Comment by prusnak** [comment]
Currently we won't be adding ECDH to the library. You might want to check https://github.com/ARMmbed/mbedtls which is TLS oriented and thus has ECDH (and secp256k1 curve as well).
