### ISSUE TITLE
Question: AES instruction set

### ISSUE THREAD

**Issue by netanelkl** [trezor/trezor-crypto#32]
I see you don't support the AES instruction set if it's the right cpu, is it because you guys work with a different architecture?

**Comment by prusnak** [comment]
Right. ARMv7 instruction set does not have AES-NI.

**Comment by netanelkl** [comment]
But ARM has NEON, vector processing is not firmware AES, but it's still faster.

You should consider copying from OpenSSL:

https://github.com/openssl/openssl/blob/master/crypto/aes/asm/aes-armv4.pl

Just suggesting :)

**Comment by prusnak** [comment]
It does not make sense to optimize AES performance for trezor-crypto, because it is used only on small set of data (less than a kilobyte).

**Comment by netanelkl** [comment]
oh ok :)
