### ISSUE TITLE
ecdsa point_multiply overread bug?

### ISSUE THREAD

**Issue by axic** [trezor/trezor-crypto#70]
```
        for (i = 62; i >= 0; i--) {
                // sign = sign(a[i+1])  (0xffffffff for negative, 0 for positive)
                // invariant jres = (-1)^sign sum_{j=i+1..63} (a[j] * 16^{j-i-1} * p)

                point_jacobian_double(&jres, curve);
                point_jacobian_double(&jres, curve);
                point_jacobian_double(&jres, curve);
                point_jacobian_double(&jres, curve);

                // get lowest 5 bits of a >> (i*4).
                pos = i*4/30; shift = i*4 % 30;
                bits = (a.val[pos+1]<<(30-shift) | a.val[pos] >> shift) & 31;
```

On the first iteration (`i = 62`) it tries to access `a.val[9]`, which is out of bounds. (`(62 * 4 / 30) + 1`).

**Comment by prusnak** [comment]
CC @jhoenicke

**Comment by spudowiar** [comment]
https://github.com/trezor/trezor-crypto/blob/master/ecdsa.c#L493-L504

**Comment by axic** [comment]
To be honest, given `& 31`, the random value from memory at `val[9]` will not change the calculation, but it still reads from an invalid location.

And sorry, forgot to put in the file link :)

**Comment by jhoenicke** [comment]
Yes, you  are right.  I thought there would be enough extra space but it still reads beyond the end.  For Trezor it never causes problem (except maybe in the very unlikely case that the firmware fits exactly into the flash and there is a big number at the end of the firmware), but I'll fix it.
